server:
  port: ${PORT:8080}

spring:
  application:
    name: programming-language-api
  data:
    mongodb:
      database: language-api
      uri: ${DATABASE_URL:mongodb+srv://laurosilveira:6wa0qALShtUKe9NW@languagi-api.cp7sbjb.mongodb.net/?retryWrites=true&w=majority}

  devtools:
    restart:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html