spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      database: language-api
      uri: ${DATABASE_PRO:mongodb+srv://laurosilveira:AuCatsHoTxGHRdYW@languagi-api.cp7sbjb.mongodb.net/?retryWrites=true&w=majority}

springdoc:
  swagger-ui:
    path: /swagger-ui.html