spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      uri: mongodb+srv://alura:mnkypl9IUBgIF3pK@aluradb.oqouams.mongodb.net/aluradb?retryWrites=true&w=majority
springdoc:
  .swagger-ui:
  path: /swagger-ui.html