server:
  port: 8080

spring:
  application:
    name: programming-language-api
  data:
    mongodb:
      database: language-api
      uri: ${DATABASE_URL}

  devtools:
    restart:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html